Feedback Showing view
DeveloperAcademy-POSTECH/MC2-Team15-MeetingNMusae pull request #40
Opened 2022-06-17 01:48 UTC by tea-hkim

## 작업 내용

1. 

## 고민한 내용

## 리뷰 받고 싶은 내용 ( 질문할 내용 )

2022-06-17 07:36 UTC, cozytk requested changes
pbxproj conflict 이씁니다

2022-06-17 07:36 UTC, cozytk commented on MeetingNMusae/MeetingNMusae/Views/ReviewShowingView.swift
> +                }
이 뷰파일은 예시코드 성격이라서 main에 올라가도 되는 건지 잘 모르겠지만,, 전 괜찮을 것 같습니다!!

2022-06-18 04:52 UTC, tea-hkim commented on MeetingNMusae/MeetingNMusae/Views/ReviewShowingView.swift
> +                }
동의합니다
UI만 만들어진 상태라서 fireStore랑 연동하는 브랜치가 생겨서 작업이 끝나면 연결하겠습니다

2022-06-19 17:08 UTC, cozytk approved these changes

2022-06-19 17:08 UTC, merged